version: '3.9'

services:
  webclient:
    build:
      context: frontend
      dockerfile: Dockerfile.netlify
      args:
        BACKEND_URL: https://thetruestore.herokuapp.com/
        NETLIFY_ACCESS_TOKEN: setup_in_github_secrets
        NETLIFY_SUBDOMAIN: thetruestore
    container_name: webclient