version: '3.9'

volumes:
  postgres_data:

services:
  storage:
    image: 'postgres:13.7'
    container_name: storage
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ 'CMD-SHELL', 'su postgres', '&&', 'pg_isready' ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: truestore
      POSTGRES_PASSWORD: password

  backendapp:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: backendapp
    ports:
      - '8080:8080'
    depends_on:
      storage:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://storage:5432/truestore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRINT_DATASOURCE_PASSWORD=password
    volumes:
      - '/etc/localtime:/etc/localtime:ro'